version: '3.8'

services:
  ped-practice:
    build: .
    container_name: ped-practice
    restart: always
    networks:
      - platform-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ped.rule=Host(`ped.kampuz.kz`)"
      - "traefik.http.routers.ped.service=ped"
      - "traefik.http.services.ped.loadbalancer.server.port=80"
      - "traefik.docker.network=platform-net"

networks:
  platform-net:
    external: true
